### ISSUE TITLE
Segfault on opening

### ISSUE THREAD

**Issue by DigiAngel** [birdieapp/birdie#138]
Starting birdie gives me:
~~~
[_LEVEL_INFO 07:41:20.771229] Birdie.vala:194: Birdie version: 1.1
[_LEVEL_INFO 07:41:20.771286] Birdie.vala:196: Kernel version: 3.13.0-68-generic
[_LEVEL_DEBUG 07:41:20.783520] Indicator.vala:34: Registered messaging-menu
[_LEVEL_FATAL 07:41:21.461596] Twitter.vala:343: Authorization Required
[_LEVEL_FATAL 07:41:21.461688] birdie will not function properly.
Segmentation fault (core dumped)
~~~

backtrace:
~~~
#0  0x000000000043110f in birdie_widgets_tweet_box_construct ()
No symbol table info available.
#1  0x0000000000433a09 in birdie_widgets_tweet_list_append ()
No symbol table info available.
#2  0x00007ffff2790648 in g_list_foreach () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x000000000042d56c in birdie_cache_load_cached_tweets ()
No symbol table info available.
#4  0x0000000000416191 in ?? ()
No symbol table info available.
#5  0x00007ffff27b8f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007ffff1478182 in start_thread (arg=0x7fffc2df8700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7fffc2df8700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736462817024, 1697164096432382334, 1, 0, 140736462817728, 140736462817024, -1697280374039240322, -1697176118358171266}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007ffff214b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
~~~

**Comment by DigiAngel** [comment]
Meh...fixed up with removing old ~/.local/share/birdie dir.
