### ISSUE TITLE
Rarely, tweets don't load at startup (_strptime error)

### ISSUE THREAD

**Issue by contribucious** [birdieapp/birdie#85]
**First time I have that:**
At startup, no tweets loaded, just the '+' button shown at the top of the application. A simple restart of the application solved this problem.

But here was the logs (check the 2 lines at the end):
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "[FULL-PATH-HERE]/birdie/birdieapp/application.py", line 397, in get_home_timeline
    cb(data)
  File "[FULL-PATH-HERE]/birdie/birdieapp/application.py", line 401, in get_home_timeline_cb
    self.on_new_tweet_received(data[x], False)
  File "[FULL-PATH-HERE]/birdie/birdieapp/application.py", line 652, in on_new_tweet_received
    self.add_to_list(data, self.home_tweet_list, stream)
  File "[FULL-PATH-HERE]/birdie/birdieapp/application.py", line 920, in add_to_list
    box = TweetBox(data, self.active_account)
  File "[FULL-PATH-HERE]/birdie/birdieapp/gui/tweetbox.py", line 67, in __init__
    self.set_user_name_box()
  File "[FULL-PATH-HERE]/birdie/birdieapp/gui/tweetbox.py", line 291, in set_user_name_box
    datetime = twitter_date_to_datetime(self.data['created_at'])
  File "[FULL-PATH-HERE]/birdie/birdieapp/utils/timecalc.py", line 59, in twitter_date_to_datetime
    created_at = datetime.strptime(tweet_date, "%a %b %d %H:%M:%S +0000 %Y")
AttributeError: _strptime
```

**I found these related links about this '_strptime' error:**
- http://bugs.python.org/issue11108
- http://code-trick.com/python-bug-attribute-error-_strptime/

**TECHNICAL INFO:**
- Birdie version: _2.0-dev_
- Python version: _2.7.5-5ubuntu3_
- OS: _Netrunner 14 (based on Ubuntu 14.04)_

**Comment by nathandyer** [comment]
Hi! This issue has been fixed in Birdie 2.0, which is no longer in Python. Thank you for the report! Cheers!
